ping-config:
   server: eu
   env-id: <<REPLACE>>
   oidc-client-id: <<REPLACE>>
   oidc-client-secret: <<REPLACE>>
   oidc-client-redirect-uri: http://localhost:8080/login/oauth2/code/ping
   trx-approval:
      policy: trx_approval
      template: transaction
   profile-page: https://apps.pingone.${ping-config.server}/${ping-config.env-id}/myaccount
   auth-flow-url: https://auth.pingone.${ping-config.server}/${ping-config.env-id}/flows
   issuer-uri: https://auth.pingone.${ping-config.server}/${ping-config.env-id}/as
   az-server-az-url: ${ping-config.issuer-uri}/authorize
      
server:
  port: 8080

logging:
  level:
    root: INFO
    com.pingidentity.oidclogin: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    

spring:
  security:
    oauth2:
      client:
        registration:
          ping:
            client-id: ${ping-config.oidc-client-id}
            client-secret: ${ping-config.oidc-client-secret}
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          ping:
            issuer-uri: ${ping-config.issuer-uri}


